### ISSUE TITLE
로그인 할 때 프로필 사진 URL도 받기

### ISSUE THREAD

**Issue by Noverish** [mash-up-kr/checkmate-backend#8]

**Comment by jo-bata** [comment]
사이드 메뉴에서 프로필 사진 보여주는 기능 좋은 것 같습니다.
카카오톡 연동 ios 개발가이드를 보면
 - profile_image: 카카오톡 또는 카카오스토리의 프로필 이미지 URL
 - thumbnail_image: 프로필 이미지의 썸네일 URL

가 있는데 둘중 어떤걸로 url을 받는게 좋을까요?
