### ISSUE TITLE
[메인 화면 조회하기]에 필요한 정보

### ISSUE THREAD

**Issue by Noverish** [mash-up-kr/checkmate-backend#9]
[메인 화면 조회하기] 에서 Workspace id를 받아야 합니다.
홈 화면에는 여러 Workspace가 나오기 때문이죠
그리고

지금 WorkSpace의 이번 달 일한 시간
지금 WorkSpace의 시급

이 필요합니다.

**Comment by jo-bata** [comment]
지금은 조회하기 이전에 [전체 근무지 조회하기] api를 먼저 불러와서 얻어낸 workspace id로 해결하고 있습니다.
세분화가 필요한 부분 같네요.
요청 uri와 response 수정하겠습니다.
